name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8.0.332+9
        cache: 'maven'
    - name: Build and test with JaCoCo
      run: mvn -B clean package --file ./**/pom.xml
    coverage:
      needs: build
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 15
        - run: mvn -B verify -P coverage --no-transfer-progress

        - uses: codecov/codecov-action@v1
          with:
            file: ./**/target/site/jacoco/jacoco.xml
            name: codecov

